# Generated by Django 6.0.6 on 2026-07-09 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='О нас', max_length=200, verbose_name='Заголовок страницы')),
                ('title_ru', models.CharField(default='О нас', max_length=200, null=True, verbose_name='Заголовок страницы')),
                ('title_en', models.CharField(default='О нас', max_length=200, null=True, verbose_name='Заголовок страницы')),
                ('title_hy', models.CharField(default='О нас', max_length=200, null=True, verbose_name='Заголовок страницы')),
                ('content', models.TextField(verbose_name='История проекта')),
                ('content_ru', models.TextField(null=True, verbose_name='История проекта')),
                ('content_en', models.TextField(null=True, verbose_name='История проекта')),
                ('content_hy', models.TextField(null=True, verbose_name='История проекта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Фото для страницы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': "Страница 'О нас'",
                'verbose_name_plural': "Страницы 'О нас'",
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название проекта')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название проекта')),
                ('title_hy', models.CharField(max_length=200, null=True, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_hy', models.TextField(null=True, verbose_name='Описание')),
                ('year', models.IntegerField(verbose_name='Год реализации')),
                ('trees_planted', models.IntegerField(default=0, verbose_name='Посажено деревьев')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен сейчас')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Заявка волонтера',
                'verbose_name_plural': 'Заявки волонтеров',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Фото')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Фото проекта',
                'verbose_name_plural': 'Фото проектов',
                'ordering': ['order'],
            },
        ),
    ]
