# Generated by Django 6.0.6 on 2026-07-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='address_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_hy',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='description_en',
            field=models.TextField(blank=True, default='Aragats Antar — восстанавливаем леса Армении для будущих поколений.', null=True, verbose_name='Краткое описание для футера'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='description_hy',
            field=models.TextField(blank=True, default='Aragats Antar — восстанавливаем леса Армении для будущих поколений.', null=True, verbose_name='Краткое описание для футера'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='description_ru',
            field=models.TextField(blank=True, default='Aragats Antar — восстанавливаем леса Армении для будущих поколений.', null=True, verbose_name='Краткое описание для футера'),
        ),
    ]
