# Generated by Django 6.0.6 on 2026-08-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactinfo_address_en_contactinfo_address_hy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.SlugField(verbose_name='Идентификатор страницы (например, join)')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('hy', 'Հայերեն')], max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок / Описание')),
            ],
            options={
                'verbose_name': 'Текст страницы',
                'verbose_name_plural': 'Тексты страниц',
                'unique_together': {('page_slug', 'language')},
            },
        ),
    ]
