# Generated by Django 6.0.6 on 2026-08-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(default='Присоединяйтесь к нам!', max_length=200, verbose_name='Заголовок (русский)')),
                ('subtitle_ru', models.TextField(blank=True, default='Заполните форму ниже, чтобы стать частью команды Aragats Antar', verbose_name='Подзаголовок (русский)')),
                ('text_1_ru', models.TextField(blank=True, verbose_name='Текст 1 (русский)')),
                ('text_2_ru', models.TextField(blank=True, verbose_name='Текст 2 (русский)')),
                ('text_3_ru', models.TextField(blank=True, verbose_name='Текст 3 (русский)')),
                ('text_4_ru', models.TextField(blank=True, verbose_name='Текст 4 (русский)')),
                ('text_5_ru', models.TextField(blank=True, verbose_name='Текст 5 (русский)')),
                ('title_en', models.CharField(default='Join us!', max_length=200, verbose_name='Заголовок (english)')),
                ('subtitle_en', models.TextField(blank=True, default='Fill out the form below to become part of the Aragats Antar team', verbose_name='Подзаголовок (english)')),
                ('text_1_en', models.TextField(blank=True, verbose_name='Текст 1 (english)')),
                ('text_2_en', models.TextField(blank=True, verbose_name='Текст 2 (english)')),
                ('text_3_en', models.TextField(blank=True, verbose_name='Текст 3 (english)')),
                ('text_4_en', models.TextField(blank=True, verbose_name='Текст 4 (english)')),
                ('text_5_en', models.TextField(blank=True, verbose_name='Текст 5 (english)')),
                ('title_hy', models.CharField(default='Միացեք մեզ!', max_length=200, verbose_name='Заголовок (հայերեն)')),
                ('subtitle_hy', models.TextField(blank=True, default='Լրացրեք ստորև բերված ձևը՝ Aragats Antar-ի թիմի մաս դառնալու համար', verbose_name='Подзаголовок (հայերեն)')),
                ('text_1_hy', models.TextField(blank=True, default='«<strong>Aragats Antar</strong>»-ը պարզապես անտառների վերականգնման ծրագիր չէ։ Այն համախոհների համայնք է, որտեղ յուրաքանչյուրը կարող է գտնել իր տեղը և իրական ներդրում ունենալ Հայաստանի բնության և կլիմայի պահպանման գործում։', verbose_name='Текст 1 (հայերեն)')),
                ('text_2_hy', models.TextField(blank=True, default='Մենք փնտրում ենք <strong>ագրոնոմների և դենդրոլոգների</strong>։ Մեզ անհրաժեշտ են <span class="brand-color"><strong>կամավոր-կանաչապատողներ</strong></span>, ովքեր պատրաստ են մասնակցել շաբաթօրյակներին, տնկել ծառեր և խնամել տնկիները։', verbose_name='Текст 2 (հայերեն)')),
                ('text_3_hy', models.TextField(blank=True, default='Եթե դուք <span class="brand-color"><strong>SMM մասնագետ</strong></span> եք, մենք ձեզ կվստահենք սոցիալական ցանցերի վարումը և բովանդակության ստեղծումը։ <strong>Քոփիռայթերները</strong> կօգնեն մեզ գրել տեքստեր կայքի և ԶԼՄ-ների համար։ <span class="brand-color"><strong>Կոնտենտ ստեղծողները և լուսանկարիչները</strong></span> կնկարահանեն տեսանյութեր ու լուսանկարներ՝ ցուցադրելով Արագածի գեղեցկությունն ու անտառների վերականգնման ընթացքը։', verbose_name='Текст 3 (հայերեն)')),
                ('text_4_hy', models.TextField(blank=True, default='Իսկ եթե ունեք այլ մասնագիտություններ՝ դիզայն, իրավաբանություն, հաշվապահություն, լոգիստիկա կամ այլ ոլորտներ, վստահ ենք՝ ձեր գիտելիքներն ու փորձը նույնպես կարող են կարևոր ներդրում ունենալ մեր առաքելության մեջ։', verbose_name='Текст 4 (հայերեն)')),
                ('text_5_hy', models.TextField(blank=True, default='<strong>Ի՞նչ կստանաք դուք։</strong> Իրական փորձ, նոր ծանոթություններ, եզակի լուսանկարներ լեռների ֆոնին, պորտֆոլիոյի համալրում և գիտակցում, որ դուք ավելի լավն եք դարձնում աշխարհը։ Յուրաքանչյուր տնկած ծառը ձեր անձնական ներդրումն է Հայաստանի ապագայում։', verbose_name='Текст 5 (հայերեն)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': "Страница 'Присоединиться'",
                'verbose_name_plural': "Страница 'Присоединиться'",
            },
        ),
        migrations.DeleteModel(
            name='PageContent',
        ),
    ]
